APP_NAME: "profilemgr"
APP_PORT: "8000"

DB_DRIVER: "postgres"
DB_HOST: "localhost"
DB_PORT: 5432
DB_NAME: "profilemgr"
DB_USER: "postgres"
DB_PASSWORD: ""
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: "./migrations"
